/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosIndexRouteImport } from './routes/scenarios.index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as ScenariosIdRouteImport } from './routes/scenarios.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIndexRoute = ScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosIdRoute = ScenariosIdRouteImport.update({
  id: '/scenarios/$id',
  path: '/scenarios/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/scenarios': typeof ScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/simulator': typeof SimulatorRoute
  '/terms': typeof TermsRoute
  '/scenarios/$id': typeof ScenariosIdRoute
  '/share/$slug': typeof ShareSlugRoute
  '/scenarios/': typeof ScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/scenarios/$id'
    | '/share/$slug'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/scenarios/$id'
    | '/share/$slug'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/privacy'
    | '/simulator'
    | '/terms'
    | '/scenarios/$id'
    | '/share/$slug'
    | '/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SimulatorRoute: typeof SimulatorRoute
  TermsRoute: typeof TermsRoute
  ScenariosIdRoute: typeof ScenariosIdRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ScenariosIndexRoute: typeof ScenariosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/': {
      id: '/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof ScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$id': {
      id: '/scenarios/$id'
      path: '/scenarios/$id'
      fullPath: '/scenarios/$id'
      preLoaderRoute: typeof ScenariosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SimulatorRoute: SimulatorRoute,
  TermsRoute: TermsRoute,
  ScenariosIdRoute: ScenariosIdRoute,
  ShareSlugRoute: ShareSlugRoute,
  ScenariosIndexRoute: ScenariosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
